# Move package configuration for HetraCoin on Sui
[package]
name = "hetracoin-sui"
version = "0.1.0"
published-at = "0x0"
authors = ["Hetrafi Dev Team"]
edition = "2024"

# Dependencies
[dependencies]
# TESTS PASSING WITH VERSION 1.44.3
Sui = { local = "../sui/crates/sui-framework/packages/sui-framework" }

# Address placeholders
[addresses]
hetracoin = "0x0"
hetracoin_unit = "0x0"
hetracoin_integration = "0x0"
