# Move package configuration for HetraCoin on Sui
[package]
name = "hetracoin-sui"
version = "0.1.0"
published-at = "0x0"
authors = ["HetraFi Development Team"]
edition = "2024"

# Dependencies
[dependencies]
Sui = { git = "https://github.com/MystenLabs/sui.git", subdir = "crates/sui-framework/packages/sui-framework", rev = "devnet" }

# Address placeholders
[addresses]
hetracoin = "0x0"
hetracoin_unit = "0x0"
hetracoin_integration = "0x0"
